apiVersion: v1
kind: Pod
metadata: 
     name: myapp-pod
     labels:
             app: myapp
             type: fron-tend
spec:  
    containers:
       - name: nginx-container
         image: nginx

